/*
 * Jwt payload type
 */
export type TJwtPayload = {
	userId: string;
};
/*
 * Interface for AuthService. The JWT token is generated by Supabase.
 * The JWT secret is stored in the AmbianceConfig provided also by Supabase.
 */
export type TAuthService = {
	/**
	 * Get the JWT secret from the instance.
	 */
	readonly getJwtSecret: () => string;
	/**
	 * Validates a JWT token.
	 */
	readonly validateJwt: (args: TValidateJwtArgs) => TJwtPayload | null;
	/**
	 * Decodes a JWT token.
	 */
	readonly decodeJwt: (args: TDecodeJwtArgs) => TJwtPayload | null;
};
